# -*- coding: utf-8 -*-
# Generated by Django 1.9.12 on 2017-06-23 20:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0003_article_score'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='meta_description',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='\u041c\u0435\u0442\u0430-\u0442\u0435\u0433 Description'),
        ),
        migrations.AddField(
            model_name='article',
            name='title_tag',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='HTML-\u0442\u0435\u0433 Title'),
        ),
    ]
