# -*- coding: utf-8 -*-
# Generated by Django 1.9.12 on 2017-02-06 18:54
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('catalogue', '0013_productpackage_count'),
    ]

    operations = [
        migrations.CreateModel(
            name='FavoriteList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Default', max_length=255, verbose_name='Name')),
                ('key', models.CharField(db_index=True, editable=False, max_length=6, unique=True, verbose_name='Key')),
                ('date_created', models.DateTimeField(auto_now_add=True, verbose_name='Date created')),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='favoritelists', to=settings.AUTH_USER_MODEL, verbose_name='Owner')),
            ],
            options={
                'ordering': ('date_created',),
                'verbose_name': '\u0421\u043f\u0438\u0441\u043e\u043a \u0436\u0435\u043b\u0430\u0435\u043c\u043e\u0433\u043e',
                'verbose_name_plural': '\u0421\u043f\u0438\u0441\u043a\u0438 \u0436\u0435\u043b\u0430\u0435\u043c\u043e\u0433\u043e',
            },
        ),
        migrations.CreateModel(
            name='FavoriteListLine',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1, verbose_name='Quantity')),
                ('title', models.CharField(max_length=255, verbose_name='Title')),
                ('favlist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='favoritelist.FavoriteList', verbose_name='\u0421\u043f\u0438\u0441\u043e\u043a \u0436\u0435\u043b\u0430\u0435\u043c\u043e\u0433\u043e')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='favlist_lines', to='catalogue.Product', verbose_name='Product')),
            ],
            options={
                'ordering': ['pk'],
                'verbose_name': 'Wish list line',
            },
        ),
        migrations.AlterUniqueTogether(
            name='favoritelistline',
            unique_together=set([('favlist', 'product')]),
        ),
    ]
