# -*- coding: utf-8 -*-
# Generated by Django 1.9.12 on 2017-09-08 21:40
from __future__ import unicode_literals

from django.db import migrations


def create_handpicked(apps, list_name):
    HandPickedProductList = apps.get_model("promotions", "HandPickedProductList")
    try:
        HandPickedProductList.objects.get(name=list_name)
    except HandPickedProductList.DoesNotExist:
        HandPickedProductList(name=list_name).save()


def create_popular_handpicked(apps, schema_editor):
    create_handpicked(apps, u'Популярное')


def create_recommended_handpicked(apps, schema_editor):
    create_handpicked(apps, u'Рекомендуемое')


class Migration(migrations.Migration):
    dependencies = [
        ('promotions', '0002_auto_20150604_1450'),
    ]

    operations = [
        migrations.RunPython(create_popular_handpicked),
        migrations.RunPython(create_recommended_handpicked)
    ]
