# -*- coding: utf-8 -*-
# Generated by Django 1.9.12 on 2017-01-19 13:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0002_auto_20170119_1210'),
    ]

    operations = [
        migrations.AddField(
            model_name='multipleoption',
            name='display_type',
            field=models.CharField(choices=[(b'radio', b'radio'), (b'select', b'select')], default=b'radio', max_length=100),
        ),
    ]
