# -*- coding: utf-8 -*-
# Generated by Django 1.9.12 on 2017-01-19 16:17
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0009_slugfield_noop'),
    ]

    operations = [
        migrations.CreateModel(
            name='MultipleOption',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('display_type', models.CharField(choices=[(b'radio', b'radio'), (b'select', b'select')], default=b'radio', max_length=100)),
            ],
            options={
                'verbose_name': '\u041c\u043d\u043e\u0436\u0435\u0441\u0442\u0432\u0435\u043d\u043d\u0430\u044f \u043e\u043f\u0446\u0438\u044f',
                'verbose_name_plural': '\u041c\u043d\u043e\u0436\u0435\u0441\u0442\u0432\u0435\u043d\u043d\u044b\u0435 \u043e\u043f\u0446\u0438\u0438',
            },
        ),
        migrations.CreateModel(
            name='OptionGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='\u041d\u0430\u0437\u0432\u0430\u043d\u0438\u0435 \u0433\u0440\u0443\u043f\u044b')),
                ('code', models.CharField(help_text='\u0422\u043e\u043b\u044c\u043a\u043e \u043b\u0430\u0442\u0438\u043d\u0441\u043a\u0438\u0435 \u0441\u0438\u043c\u0432\u043e\u043b\u044b', max_length=100, verbose_name='\u041a\u043e\u0434 \u0433\u0440\u0443\u043f\u044b')),
            ],
            options={
                'verbose_name': '\u0413\u0440\u0443\u043f\u0430 \u043e\u043f\u0446\u0438\u0439',
                'verbose_name_plural': '\u0413\u0440\u0443\u043f\u044b \u043e\u043f\u0446\u0438\u0439',
            },
        ),
        migrations.CreateModel(
            name='OptionVariant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='\u041d\u0430\u0437\u0432\u0430\u043d\u0438\u0435')),
                ('image', models.ImageField(blank=True, upload_to=b'options_image', verbose_name='\u0418\u0437\u043e\u0431\u0440\u0430\u0436\u0435\u043d\u0438\u0435')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variants', to='catalogue.OptionGroup', verbose_name='\u0413\u0440\u0443\u043f\u0430')),
            ],
            options={
                'verbose_name': '\u0412\u0430\u0440\u0438\u0430\u043d\u0442',
                'verbose_name_plural': '\u0412\u0430\u0440\u0438\u0430\u043d\u0442\u044b',
            },
        ),
        migrations.AddField(
            model_name='multipleoption',
            name='choices',
            field=models.ManyToManyField(to='catalogue.OptionVariant', verbose_name='\u0412\u0430\u0440\u0438\u0430\u043d\u0442\u044b'),
        ),
        migrations.AddField(
            model_name='multipleoption',
            name='group',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='Choices', to='catalogue.OptionGroup', verbose_name='\u0413\u0440\u0443\u043f\u0430 \u043e\u043f\u0446\u0438\u0439'),
        ),
        migrations.AddField(
            model_name='multipleoption',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='multiple_options', to='catalogue.Product', verbose_name='\u0422\u043e\u0432\u0430\u0440'),
        ),
    ]
