# -*- coding: utf-8 -*-
# Generated by Django 1.9.12 on 2017-01-21 00:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0010_auto_20170119_1617'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='multipleoption',
            name='display_type',
        ),
        migrations.AddField(
            model_name='optiongroup',
            name='display_type',
            field=models.CharField(choices=[(b'radio', b'radio'), (b'select', b'select')], default=b'radio', max_length=100, verbose_name='\u0422\u0438\u043f \u043e\u0442\u043e\u0431\u0440\u0430\u0436\u0435\u043d\u0438\u044f'),
        ),
        migrations.AddField(
            model_name='optiongroup',
            name='preview',
            field=models.BooleanField(default=False),
        ),
    ]
