# -*- coding: utf-8 -*-
# Generated by Django 1.9.12 on 2017-02-03 12:07
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0010_auto_20170201_0049'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductPackage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('package_num', models.IntegerField(verbose_name='\u041d\u043e\u043c\u0435\u0440 \u0443\u043f\u0430\u043a\u043e\u0432\u043a\u0438')),
                ('upc', models.CharField(max_length=20, verbose_name='\u0410\u0440\u0442\u0438\u043a\u0443\u043b')),
                ('name', models.CharField(max_length=100, verbose_name='\u041d\u0430\u0438\u043c\u0435\u043d\u043e\u0432\u0430\u043d\u0438\u0435 \u0443\u043f\u0430\u043a\u043e\u0432\u043a\u0438')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='packages', to='catalogue.Product', verbose_name='\u0422\u043e\u0432\u0430\u0440')),
            ],
            options={
                'verbose_name': '\u0423\u043f\u0430\u043a\u043e\u0432\u043a\u0430',
                'verbose_name_plural': '\u0423\u043f\u0430\u043a\u043e\u0432\u043a\u0438',
            },
        ),
    ]
