# -*- coding: utf-8 -*-
# Generated by Django 1.9.12 on 2017-02-03 12:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0011_productpackage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productpackage',
            name='package_num',
            field=models.IntegerField(default=1, verbose_name='\u041d\u043e\u043c\u0435\u0440 \u0443\u043f\u0430\u043a\u043e\u0432\u043a\u0438'),
        ),
    ]
