# -*- coding: utf-8 -*-
# Generated by Django 1.9.12 on 2017-02-03 12:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0012_auto_20170203_1226'),
    ]

    operations = [
        migrations.AddField(
            model_name='productpackage',
            name='count',
            field=models.IntegerField(default=1, verbose_name='\u041a\u043e\u043b\u0438\u0447\u0435\u0441\u0442\u0432\u043e \u0443\u043f\u0430\u043a\u043e\u0432\u043e\u043a'),
        ),
    ]
