# -*- coding: utf-8 -*-
# Generated by Django 1.9.12 on 2017-01-21 00:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0013_auto_20170121_0022'),
    ]

    operations = [
        migrations.AddField(
            model_name='optiongroup',
            name='postfix',
            field=models.CharField(blank=True, max_length=5, null=True, verbose_name='\u041f\u043e\u0441\u0442\u0444\u0438\u043a\u0441'),
        ),
    ]
