# -*- coding: utf-8 -*-
# Generated by Django 1.9.12 on 2017-01-21 00:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0014_optiongroup_postfix'),
    ]

    operations = [
        migrations.AlterField(
            model_name='optiongroup',
            name='postfix',
            field=models.CharField(blank=True, default='', max_length=5, verbose_name='\u041f\u043e\u0441\u0442\u0444\u0438\u043a\u0441'),
            preserve_default=False,
        ),
    ]
