# -*- coding: utf-8 -*-
# Generated by Django 1.9.12 on 2017-02-20 23:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0015_auto_20170210_1509'),
    ]

    operations = [
        migrations.AddField(
            model_name='multipleoption',
            name='required',
            field=models.BooleanField(default=True, verbose_name='\u041e\u0431\u044f\u0437\u0430\u0442\u0435\u043b\u044c\u043d\u043e\u0435 \u043f\u043e\u043b\u0435 ?'),
        ),
    ]
