# -*- coding: utf-8 -*-
# Generated by Django 1.9.12 on 2017-02-20 23:29
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0016_multipleoption_required'),
    ]

    operations = [
        migrations.RenameField(
            model_name='multipleoption',
            old_name='required',
            new_name='is_required',
        ),
    ]
