# -*- coding: utf-8 -*-
# Generated by Django 1.9.12 on 2017-01-26 14:07
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0016_auto_20170121_0052'),
    ]

    operations = [
        migrations.CreateModel(
            name='OptionInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('additional_price', models.IntegerField(verbose_name='\u041d\u0430\u0446\u0435\u043d\u043a\u0430')),
            ],
        ),
        migrations.RemoveField(
            model_name='multipleoption',
            name='choices',
        ),
        migrations.AddField(
            model_name='optioninfo',
            name='multi_option',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='choices', to='catalogue.MultipleOption', verbose_name=b''),
        ),
        migrations.AddField(
            model_name='optioninfo',
            name='variant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='infos', to='catalogue.OptionVariant', verbose_name='\u0412\u0430\u0440\u0438\u0430\u043d\u0442'),
        ),
    ]
