# -*- coding: utf-8 -*-
# Generated by Django 1.9.12 on 2017-03-01 12:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0017_auto_20170220_2329'),
    ]

    operations = [
        migrations.AddField(
            model_name='optiongroup',
            name='is_filter',
            field=models.BooleanField(default=True, verbose_name='\u0424\u0438\u043b\u044c\u0442\u0440\u043e\u0432\u0430\u0442\u044c?'),
        ),
    ]
