# -*- coding: utf-8 -*-
# Generated by Django 1.9.12 on 2017-01-26 14:21
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0017_auto_20170126_1407'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='optioninfo',
            options={'verbose_name': '\u0418\u043d\u0444\u043e\u0440\u043c\u0430\u0446\u0438\u044f \u043e\u043f\u0446\u0438\u0438', 'verbose_name_plural': '\u0418\u043d\u0444\u043e\u0440\u043c\u0430\u0446\u0438\u0438 \u043e\u043f\u0446\u0438\u0439'},
        ),
    ]
