# -*- coding: utf-8 -*-
# Generated by Django 1.9.12 on 2017-01-26 18:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0018_auto_20170126_1421'),
    ]

    operations = [
        migrations.AlterField(
            model_name='optioninfo',
            name='additional_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='\u041d\u0430\u0446\u0435\u043d\u043a\u0430'),
        ),
    ]
