# -*- coding: utf-8 -*-
# Generated by Django 1.9.12 on 2017-07-20 18:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0020_make_dop_nullable'),
    ]

    operations = [
        migrations.AlterField(
            model_name='optiongroup',
            name='display_type',
            field=models.CharField(choices=[(b'radio', b'radio'), (b'select', b'select'), (b'checkbox', b'checkbox')], default=b'radio', max_length=100, verbose_name='\u0422\u0438\u043f \u043e\u0442\u043e\u0431\u0440\u0430\u0436\u0435\u043d\u0438\u044f'),
        ),
    ]
