# -*- coding: utf-8 -*-
# Generated by Django 1.9.12 on 2017-09-11 18:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0022_display_dop_checkbox'),
    ]

    operations = [
        migrations.CreateModel(
            name='XMLDownloader',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=128, verbose_name='\u041a\u0440\u0430\u0442\u043a\u043e\u0435 \u043e\u043f\u0438\u0441\u0430\u043d\u0438\u0435')),
                ('xml', models.FileField(help_text='XML', upload_to=b'', verbose_name='XML \u0444\u0430\u0439\u043b')),
                ('creation_date', models.DateField(auto_now_add=True, verbose_name='\u0414\u0430\u0442\u0430 \u0441\u043e\u0437\u0434\u0430\u043d\u0438\u044f')),
            ],
            options={
                'verbose_name': 'XML \u0444\u0430\u0439\u043b',
                'verbose_name_plural': 'XML \u0444\u0430\u0439\u043b\u044b',
            },
        ),
    ]
