# -*- coding: utf-8 -*-
# Generated by Django 1.9.12 on 2017-10-13 08:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0025_remove_product_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='Services',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('free_delivery_from', models.DecimalField(decimal_places=2, max_digits=7, verbose_name='\u0411\u0435\u0441\u043f\u043b\u0430\u0442\u043d\u0430\u044f \u0434\u043e\u0441\u0442\u0430\u0432\u043a\u0430 \u043e\u0442, \u0433\u0440\u043d.')),
                ('lifting', models.DecimalField(decimal_places=2, max_digits=7, verbose_name='\u0417\u0430\u043d\u043e\u0441 \u0432 \u043a\u0432\u0430\u0440\u0442\u0438\u0440\u0443 \u043e\u0442, \u0433\u0440\u043d.')),
                ('installation', models.DecimalField(decimal_places=2, max_digits=7, verbose_name='\u0421\u0431\u043e\u0440\u043a\u0430, % \u043e\u0442 \u0441\u0442\u043e\u0438\u043c\u043e\u0441\u0442\u0438')),
                ('relevant', models.BooleanField(verbose_name='\u0410\u043a\u0442\u0443\u0430\u043b\u044c\u043d\u0430\u044f \u0438\u043d\u0444\u043e\u0440\u043c\u0430\u0446\u0438\u044f')),
            ],
            options={
                'verbose_name': '\u0418\u043d\u0444\u043e\u0440\u043c\u0430\u0446\u0438\u044f \u043e\u0431 \u0443\u0441\u043b\u0443\u0433\u0430\u0445',
                'verbose_name_plural': '\u0418\u043d\u0444\u043e\u0440\u043c\u0430\u0446\u0438\u044f \u043e\u0431 \u0443\u0441\u043b\u0443\u0433\u0430\u0445',
            },
        ),
    ]
