# -*- coding: utf-8 -*-
# Generated by Django 1.9.12 on 2017-10-29 07:50
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0028_auto_20171013_1343'),
    ]

    operations = [
        migrations.CreateModel(
            name='PackageOptionChoice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('package', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='options_choices', to='catalogue.ProductPackage', verbose_name='\u0423\u043f\u0430\u043a\u043e\u0432\u043a\u0430')),
                ('variant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='catalogue.OptionVariant', verbose_name='\u0412\u044b\u0431\u0440\u0430\u043d\u044b\u0439 \u0432\u0430\u0440\u0438\u0430\u043d\u0442')),
            ],
            options={
                'verbose_name': '\u041e\u043f\u0446\u0438\u044f \u0443\u043f\u0430\u043a\u043e\u0432\u043a\u0438',
                'verbose_name_plural': '\u041e\u043f\u0446\u0438\u0438 \u0443\u043f\u0430\u043a\u043e\u0432\u043e\u043a',
            },
        ),
        migrations.AlterModelOptions(
            name='multipleoption',
            options={'verbose_name': '\u041c\u043d\u043e\u0436\u0435\u0441\u0442\u0432\u0435\u043d\u043d\u0430\u044f \u043e\u043f\u0446\u0438\u044f \u043f\u0440\u043e\u0434\u0443\u043a\u0442\u0430', 'verbose_name_plural': '\u041c\u043d\u043e\u0436\u0435\u0441\u0442\u0432\u0435\u043d\u043d\u044b\u0435 \u043e\u043f\u0446\u0438\u0438 \u043f\u0440\u043e\u0434\u0443\u043a\u0442\u0430'},
        ),
    ]
