# -*- coding: utf-8 -*-
# Generated by Django 1.9.12 on 2017-02-01 00:49
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('basket', '0008_auto_20170201_0049'),
        ('order', '0005_update_email_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='SimpleOrder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='\u0418\u043c\u044f')),
                ('phone', models.CharField(max_length=12, verbose_name='\u0422\u0435\u043b\u0435\u0444\u043e\u043d')),
                ('comment', models.TextField(blank=True, null=True, verbose_name='\u041a\u043e\u043c\u0435\u043d\u0442\u0430\u0440\u0438\u0439')),
                ('email', models.EmailField(max_length=50, verbose_name='E-mail')),
                ('region', models.CharField(max_length=50, verbose_name='\u0420\u0435\u0433\u0438\u043e\u043d')),
                ('city', models.CharField(max_length=50, verbose_name='\u0413\u043e\u0440\u043e\u0434')),
                ('address', models.CharField(max_length=100, verbose_name='\u0410\u0434\u0440\u0435\u0441')),
                ('check_blank', models.FileField(blank=True, null=True, upload_to=b'check_blanks/%Y/%m/%d')),
                ('basket', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='basket.Basket', verbose_name='\u041a\u043e\u0440\u0437\u0438\u043d\u0430')),
            ],
        ),
    ]
