# -*- coding: utf-8 -*-
# Generated by Django 1.9.12 on 2017-01-20 21:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0006_simpleorder'),
    ]

    operations = [
        migrations.AlterField(
            model_name='simpleorder',
            name='comment',
            field=models.TextField(blank=True, null=True),
        ),
    ]
