# -*- coding: utf-8 -*-
# Generated by Django 1.9.12 on 2017-02-03 17:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0006_simpleorder'),
    ]

    operations = [
        migrations.AddField(
            model_name='simpleorder',
            name='manufacture_blank',
            field=models.FileField(blank=True, null=True, upload_to=b'orders/manufature_blanks/%Y/%m/%'),
        ),
        migrations.AlterField(
            model_name='simpleorder',
            name='check_blank',
            field=models.FileField(blank=True, null=True, upload_to=b'orders/check_blanks/%Y/%m/%d'),
        ),
    ]
