# -*- coding: utf-8 -*-
# Generated by Django 1.9.12 on 2017-01-28 12:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0007_auto_20170120_2107'),
    ]

    operations = [
        migrations.AddField(
            model_name='simpleorder',
            name='check_blank',
            field=models.FileField(default=1, upload_to=b'check_blanks'),
            preserve_default=False,
        ),
    ]
