# -*- coding: utf-8 -*-
# Generated by Django 1.9.12 on 2017-02-04 16:20
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0007_auto_20170203_1700'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShippingCity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='\u0413\u043e\u0440\u043e\u0434')),
                ('shipping_price', models.DecimalField(decimal_places=2, default=0.0, max_digits=12, verbose_name='\u0421\u0442\u043e\u0438\u043c\u043e\u0441\u0442\u044c \u0434\u043e\u0441\u0442\u0430\u0432\u043a\u0438')),
            ],
        ),
        migrations.AddField(
            model_name='simpleorder',
            name='shipping_blank',
            field=models.FileField(blank=True, null=True, upload_to=b'orders/shipping_blanks/%Y/%m/%d', verbose_name='\u0411\u043b\u0430\u043d\u043a \u0434\u043e\u0441\u0442\u0430\u0432\u043a\u0438'),
        ),
        migrations.AlterField(
            model_name='simpleorder',
            name='check_blank',
            field=models.FileField(blank=True, null=True, upload_to=b'orders/check_blanks/%Y/%m/%d', verbose_name='\u0427\u0435\u043a'),
        ),
        migrations.AlterField(
            model_name='simpleorder',
            name='city',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='order.ShippingCity', verbose_name='\u0413\u043e\u0440\u043e\u0434'),
        ),
        migrations.AlterField(
            model_name='simpleorder',
            name='manufacture_blank',
            field=models.FileField(blank=True, null=True, upload_to=b'orders/manufature_blanks/%Y/%m/%d', verbose_name='\u0411\u043b\u0430\u043d\u043a \u043f\u0440\u043e\u0438\u0437\u0432\u043e\u0434\u0441\u0442\u0432\u0430'),
        ),
    ]
