# -*- coding: utf-8 -*-
# Generated by Django 1.9.12 on 2017-02-04 22:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0008_auto_20170204_1620'),
    ]

    operations = [
        migrations.AddField(
            model_name='simpleorder',
            name='order_status',
            field=models.IntegerField(choices=[(1, '\u041e\u0442\u043c\u0435\u043d\u0435\u043d'), (2, '\u0412 \u0441\u0442\u0430\u0434\u0438\u0438 \u043e\u0431\u0440\u0430\u0431\u043e\u0442\u043a\u0438'), (3, '\u041d\u0430 \u043f\u0440\u043e\u0438\u0437\u0432\u043e\u0434\u0441\u0442\u0432\u0435'), (4, '\u041e\u0433\u0440\u0443\u0436\u0435\u043d'), (5, '\u0412\u044b\u043f\u043e\u043b\u043d\u0435\u043d')], default=2, verbose_name='\u0421\u0442\u0430\u0442\u0443\u0441'),
        ),
        migrations.AddField(
            model_name='simpleorder',
            name='when_created',
            field=models.DateTimeField(auto_now_add=True, default='2016-01-01 00:00', verbose_name='\u0412\u0440\u0435\u043c\u044f \u0441\u043e\u0437\u0434\u0430\u043d\u0438\u044f'),
            preserve_default=False,
        ),
    ]
