# -*- coding: utf-8 -*-
# Generated by Django 1.9.12 on 2017-02-06 16:05
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0009_auto_20170204_2232'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='shippingcity',
            options={'verbose_name': '\u0413\u043e\u0440\u043e\u0434 \u0434\u043e\u0441\u0442\u0430\u0432\u043a\u0438', 'verbose_name_plural': '\u0413\u043e\u0440\u043e\u0434\u0430 \u0434\u043e\u0441\u0442\u0430\u0432\u043a\u0438'},
        ),
    ]
