# -*- coding: utf-8 -*-
# Generated by Django 1.9.12 on 2017-01-29 13:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0009_auto_20170128_1304'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='simpleorder',
            name='country',
        ),
        migrations.AddField(
            model_name='simpleorder',
            name='email',
            field=models.EmailField(default=1, max_length=50, verbose_name='E-mail'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='simpleorder',
            name='check_blank',
            field=models.FileField(blank=True, null=True, upload_to=b'check_blanks/%Y/%m/%d'),
        ),
    ]
