# -*- coding: utf-8 -*-
# Generated by Django 1.9.12 on 2017-01-30 18:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0010_auto_20170129_1327'),
    ]

    operations = [
        migrations.AlterField(
            model_name='simpleorder',
            name='comment',
            field=models.TextField(blank=True, null=True, verbose_name='\u041a\u043e\u043c\u0435\u043d\u0442\u0430\u0440\u0438\u0439'),
        ),
        migrations.AlterField(
            model_name='simpleorder',
            name='name',
            field=models.CharField(max_length=50, verbose_name='\u0418\u043c\u044f'),
        ),
        migrations.AlterField(
            model_name='simpleorder',
            name='phone',
            field=models.CharField(max_length=12, verbose_name='\u0422\u0435\u043b\u0435\u0444\u043e\u043d'),
        ),
    ]
