# -*- coding: utf-8 -*-
# Generated by Django 1.9.12 on 2017-10-05 09:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0012_auto_20170220_2327'),
    ]

    operations = [
        migrations.AddField(
            model_name='simpleorder',
            name='order_price',
            field=models.CharField(default=b'0.0', max_length=12, verbose_name='\u0421\u0443\u043c\u043c\u0430 \u0437\u0430\u043a\u0430\u0437\u0430'),
        ),
    ]
