# -*- coding: utf-8 -*-
# Generated by Django 1.9.12 on 2017-10-13 08:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0013_simpleorder_order_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='simpleorder',
            name='order_price',
            field=models.CharField(blank=True, default=b'0.0', max_length=12, verbose_name='\u0421\u0443\u043c\u043c\u0430 \u0437\u0430\u043a\u0430\u0437\u0430'),
        ),
    ]
