# -*- coding: utf-8 -*-
# Generated by Django 1.9.12 on 2017-01-14 23:53
from __future__ import unicode_literals

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('slider', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sliderslide',
            name='text',
            field=ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='\u0422\u0435\u043a\u0441\u0442'),
        ),
    ]
