# -*- coding: utf-8 -*-
# Generated by Django 1.9.12 on 2017-01-15 00:05
from __future__ import unicode_literals

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('slider', '0002_auto_20170114_2353'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sliderslide',
            name='link',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='\u0421\u0441\u044b\u043b\u043a\u0430'),
        ),
        migrations.AlterField(
            model_name='sliderslide',
            name='text',
            field=ckeditor.fields.RichTextField(default=1, verbose_name='\u0422\u0435\u043a\u0441\u0442'),
            preserve_default=False,
        ),
    ]
