# -*- coding: utf-8 -*-
# Generated by Django 1.9.12 on 2017-01-19 12:10
from __future__ import unicode_literals

import apps.catalogue.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0002_auto_20170119_1210'),
        ('basket', '0007_slugfield_noop'),
    ]

    operations = [
        migrations.CreateModel(
            name='LineOptionChoice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('basket_line', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='options_choices', to='basket.Line', verbose_name='\u0421\u0442\u0440\u043e\u043a\u0430 \u043a\u043e\u0440\u0437\u0438\u043d\u044b')),
                ('option', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalogue.MultipleOption', verbose_name='\u0414\u043e\u0441\u0442\u0443\u043f\u043d\u044b\u0435 \u0432\u0430\u0440\u0438\u0430\u043d\u0442\u044b')),
                ('variant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalogue.OptionVariant', validators=[apps.catalogue.models.validate_variant], verbose_name='\u0412\u044b\u0431\u0440\u0430\u043d\u044b\u0439 \u0432\u0430\u0440\u0438\u0430\u043d\u0442')),
            ],
            options={
                'verbose_name': '\u041e\u043f\u0446\u0438\u044f \u0441\u0442\u0440\u043e\u043a\u0438 \u043a\u043e\u0440\u0437\u0438\u043d\u044b',
                'verbose_name_plural': '\u041e\u043f\u0446\u0438\u0438 \u0441\u0442\u0440\u043e\u043a\u0438 \u043a\u043e\u0440\u0437\u0438\u043d',
            },
        ),
    ]
