# -*- coding: utf-8 -*-
# Generated by Django 1.9.12 on 2017-02-01 00:49
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0010_auto_20170201_0049'),
        ('basket', '0007_slugfield_noop'),
    ]

    operations = [
        migrations.CreateModel(
            name='LineOptionChoice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('basket_line', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='options_choices', to='basket.Line', verbose_name='\u0421\u0442\u0440\u043e\u043a\u0430 \u043a\u043e\u0440\u0437\u0438\u043d\u044b')),
                ('variant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='catalogue.OptionInfo', verbose_name='\u0412\u044b\u0431\u0440\u0430\u043d\u044b\u0439 \u0432\u0430\u0440\u0438\u0430\u043d\u0442')),
            ],
            options={
                'verbose_name': '\u041e\u043f\u0446\u0438\u044f \u0441\u0442\u0440\u043e\u043a\u0438 \u043a\u043e\u0440\u0437\u0438\u043d\u044b',
                'verbose_name_plural': '\u041e\u043f\u0446\u0438\u0438 \u0441\u0442\u0440\u043e\u043a\u0438 \u043a\u043e\u0440\u0437\u0438\u043d',
            },
        ),
        migrations.AlterField(
            model_name='basket',
            name='status',
            field=models.CharField(choices=[(b'Open', 'Open - currently active'), (b'Meerged', 'Merged - superceded by another basket'), (b'Saved', 'Saved - for items to be purchased later'), (b'Frozen', 'Frozen - the basket cannot be modified'), (b'Submitted', 'Submitted - has been ordered at the checkout')], default=b'Open', max_length=128, verbose_name='Status'),
        ),
    ]
