# -*- coding: utf-8 -*-
# Generated by Django 1.9.12 on 2017-01-20 12:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basket', '0008_lineoptionchoice'),
    ]

    operations = [
        migrations.AlterField(
            model_name='basket',
            name='status',
            field=models.CharField(choices=[(b'Open', 'Open - currently active'), (b'Meerged', 'Merged - superceded by another basket'), (b'Saved', 'Saved - for items to be purchased later'), (b'Frozen', 'Frozen - the basket cannot be modified'), (b'Submitted', 'Submitted - has been ordered at the checkout')], default=b'Open', max_length=128, verbose_name='Status'),
        ),
    ]
