# -*- coding: utf-8 -*-
# Generated by Django 1.9.12 on 2017-01-18 13:48
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('site_reviews', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sitereview',
            options={'ordering': ['-date_created', 'id'], 'verbose_name': '\u041e\u0442\u0437\u044b\u0432', 'verbose_name_plural': '\u041e\u0442\u0437\u044b\u0432\u044b \u043f\u0440\u043e \u0441\u0430\u0439\u0442'},
        ),
    ]
